### ISSUE TITLE
Issue installing Spline Twist Plugin on UE 4.20.1

### ISSUE THREAD

**Issue by mattferguson** [ryangadz/Workshop3_TwistCorrect#5]
Successfully repeated the issue by:

-Re-downloading and fresh install of UE 4.20.1
-Pressing "Install To Engine"
- Nothing happens, no download screen, no install progress bar.
- Confirmed it was not installed by going to "Installed plugins"

I have downloaded 19.2 and it works fine with that version, using the steps above.

Thanks!

**Comment by ryangadz** [comment]
some things got messed up on Epic's side. They fixed it and it should be downloading in 4.20.1 now. Thanks!
